nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost
              description: API over HTTP
        info:
            title: Chargeports api
            description: Api of Chargeports
            version: 1.0.0
        components:
            securitySchemes:
                apiKey:
                    type: apiKey
                    description: 'x-api-key: apiKey'
                    name: x-api-key
                    in: header
        security:
            - apiKey: []
    areas:
        path_patterns:
            - ^/api(?!/doc)
