nelmio_api_doc:
    documentation:
        info:
            title: Chargeports api
            description: Api of Chargeports
            version: 1.0.0
        securityDefinitions:
            apiKey:
                type: apiKey
                description: 'x-api-key: apiKey'
                name: x-api-key
                in: header
    areas:
        path_patterns:
            - ^/api(?!/doc.json$)
