version: '3'

services:
  db:
    container_name: chargeports_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    ports:
      - 3306:3306
    volumes:
      - ./data-mysql:/var/lib/mysql
    networks:
      - chargeports-network
  web:
    container_name: chargeports_web
    image: nginx:1.17.8
    volumes:
      - ./public:/var/www/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - chargeports-network
  app:
    container_name: chargeports_app
    build:
      context: ./docker/php
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    expose:
      - 9000
    depends_on:
      - db
    networks:
      - chargeports-network
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/db?serverVersion=5.7
networks:
  chargeports-network:
    driver: bridge
